stages:
  - test
  - release

default:
  tags:
    - lhc-apple
  image: "team-vpn-macos-14.6.1-xcode-15.4"

test:
  stage: test
  script: swift test --parallel --xunit-output tests.xml
  artifacts:
    when: always
    paths:
      - tests.xml
    reports:
      junit: tests.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

release:
  stage: release
  tags:
    - shared-small
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script: echo "Creating release $CI_COMMIT_TAG"
  release:
    tag_name: $CI_COMMIT_TAG
    description: "git-lhc $CI_COMMIT_TAG"
  rules:
    - if: $CI_COMMIT_TAG =~ /\d+/

