bodyMaxLineLength: 72
branchNameLinting:
  projectIdsInBranches: never
  projectIdRegexes:
  - '[A-Z]{2,10}-[0-9]{2,5}'
  - (^|[^\.\-\_0-9A-Z])([0-9]{3,5})
commitCategories:
- name: feat
  description: Implements a new feature.
  increment:
    minor: {}
- name: fix
  description: Fixes an issue.
- name: test
  description: Fixes or implements a test.
- name: refactor
  description: Changes code, but does not implement a fix or feature.
- name: build
  description: Changes the build system or external dependencies.
- name: doc
  description: Corrects or updates documentation for a feature or architectural decision.
- name: ci
  description: Fixes or implements a continuous integration feature.
