# tooling for builds.

.create_changelog:
  script:
    - mint run lhc changelog --show HEAD --format json --output "${LHC_CHANGELOG_PATH:-release.json}"

.create_release:
  release:
    tag_name: "$CI_COMMIT_TAG"
    description: "$CI_COMMIT_TAG_MESSAGE"

build:describe:
  script:
    - !reference [.create_changelog, script]
  artifacts:
    paths:
      - $LHC_CHANGELOG_PATH

build:fastlane:
  script:
    - !reference [build:describe, script]
    - fastlane "${LHC_FASTLANE_LANE:-build}"
  artifacts:
    paths:
      - $LHC_CHANGELOG_PATH

build:makefile:
  script:
    - !reference [build:describe, script]
    - make ${LHC_MAKEFILE_TARGET}
  artifacts:
    paths:
      - $LHC_CHANGELOG_PATH
